[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_image = "docker.io/parity/polkadot:latest"

[[relaychain.nodes]]
name = "alice"
rpc_port = 31944
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 4545

[parachains.collator]
command = "/parachain-node"
image = "registry.cn-hangzhou.aliyuncs.com/wetee_dao/wetee-node:dev.2024-12-14-20_23"
name = "wetee-dev"
rpc_port = 31945
