apiVersion: v1
kind: Service
metadata:
  name: dev-rpc
  namespace: zombie-dev
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: wetee-dev
  ports:
    - name: http
      port: 9944
      protocol: TCP
      targetPort: 9944
      nodePort: 31944