
//! Autogenerated weights for `wetee_worker`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-09-03, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-worker
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-worker/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_worker`.
pub trait WeightInfo {
	fn cluster_register() -> Weight;
	fn cluster_mortgage() -> Weight;
	fn cluster_unmortgage() -> Weight;
	fn work_proof_upload() -> Weight;
	fn cluster_withdrawal() -> Weight;
	fn cluster_stop() -> Weight;
	fn cluster_report() -> Weight;
	fn report_close() -> Weight;
	fn set_boot_peers() -> Weight;
	fn set_stage() -> Weight;
	fn upload_code() -> Weight;
	fn work_stop() -> Weight;
}

/// Weights for `wetee_worker` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn cluster_register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_047_000 picoseconds.
		Weight::from_parts(6_186_000, 0)
	}
	fn cluster_mortgage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_066_000 picoseconds.
		Weight::from_parts(5_601_000, 0)
	}
	fn cluster_unmortgage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_143_000 picoseconds.
		Weight::from_parts(5_506_000, 0)
	}
	fn work_proof_upload() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_663_000 picoseconds.
		Weight::from_parts(5_932_000, 0)
	}
	fn cluster_withdrawal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_358_000 picoseconds.
		Weight::from_parts(5_463_000, 0)
	}
	fn cluster_stop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_348_000 picoseconds.
		Weight::from_parts(5_620_000, 0)
	}
	fn cluster_report() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_487_000 picoseconds.
		Weight::from_parts(5_951_000, 0)
	}
	fn report_close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_298_000 picoseconds.
		Weight::from_parts(5_586_000, 0)
	}
	/// Storage: `WeTEEWorker::BootPeers` (r:0 w:1)
	/// Proof: `WeTEEWorker::BootPeers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_boot_peers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_442_000 picoseconds.
		Weight::from_parts(10_054_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEWorker::Stage` (r:0 w:1)
	/// Proof: `WeTEEWorker::Stage` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_stage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_319_000 picoseconds.
		Weight::from_parts(6_756_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEWorker::CodeSigner` (r:0 w:1)
	/// Proof: `WeTEEWorker::CodeSigner` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEWorker::CodeSignature` (r:0 w:1)
	/// Proof: `WeTEEWorker::CodeSignature` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn upload_code() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 17_838_000 picoseconds.
		Weight::from_parts(18_192_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn work_stop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_424_000 picoseconds.
		Weight::from_parts(5_587_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn cluster_register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_047_000 picoseconds.
		Weight::from_parts(6_186_000, 0)
	}
	fn cluster_mortgage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_066_000 picoseconds.
		Weight::from_parts(5_601_000, 0)
	}
	fn cluster_unmortgage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_143_000 picoseconds.
		Weight::from_parts(5_506_000, 0)
	}
	fn work_proof_upload() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_663_000 picoseconds.
		Weight::from_parts(5_932_000, 0)
	}
	fn cluster_withdrawal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_358_000 picoseconds.
		Weight::from_parts(5_463_000, 0)
	}
	fn cluster_stop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_348_000 picoseconds.
		Weight::from_parts(5_620_000, 0)
	}
	fn cluster_report() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_487_000 picoseconds.
		Weight::from_parts(5_951_000, 0)
	}
	fn report_close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_298_000 picoseconds.
		Weight::from_parts(5_586_000, 0)
	}
	/// Storage: `WeTEEWorker::BootPeers` (r:0 w:1)
	/// Proof: `WeTEEWorker::BootPeers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_boot_peers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_442_000 picoseconds.
		Weight::from_parts(10_054_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEWorker::Stage` (r:0 w:1)
	/// Proof: `WeTEEWorker::Stage` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_stage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_319_000 picoseconds.
		Weight::from_parts(6_756_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEWorker::CodeSigner` (r:0 w:1)
	/// Proof: `WeTEEWorker::CodeSigner` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEWorker::CodeSignature` (r:0 w:1)
	/// Proof: `WeTEEWorker::CodeSignature` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn upload_code() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 17_838_000 picoseconds.
		Weight::from_parts(18_192_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn work_stop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_424_000 picoseconds.
		Weight::from_parts(5_587_000, 0)
	}
}