
//! Autogenerated weights for `wetee_worker`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-08-21, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-worker
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-worker/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_worker`.
pub trait WeightInfo {
	fn cluster_register() -> Weight;
	fn cluster_mortgage() -> Weight;
	fn cluster_unmortgage() -> Weight;
	fn work_proof_upload() -> Weight;
	fn cluster_withdrawal() -> Weight;
	fn cluster_stop() -> Weight;
	fn cluster_report() -> Weight;
	fn report_close() -> Weight;
	fn set_boot_peers() -> Weight;
	fn set_stage() -> Weight;
	fn upload_code() -> Weight;
	fn work_stop() -> Weight;
}

/// Weights for `wetee_worker` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn cluster_register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_962_000 picoseconds.
		Weight::from_parts(6_126_000, 0)
	}
	fn cluster_mortgage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_776_000 picoseconds.
		Weight::from_parts(5_025_000, 0)
	}
	fn cluster_unmortgage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_788_000 picoseconds.
		Weight::from_parts(5_059_000, 0)
	}
	fn work_proof_upload() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_155_000 picoseconds.
		Weight::from_parts(5_333_000, 0)
	}
	fn cluster_withdrawal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_980_000 picoseconds.
		Weight::from_parts(5_428_000, 0)
	}
	fn cluster_stop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_941_000 picoseconds.
		Weight::from_parts(5_266_000, 0)
	}
	fn cluster_report() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_211_000 picoseconds.
		Weight::from_parts(5_446_000, 0)
	}
	fn report_close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_868_000 picoseconds.
		Weight::from_parts(5_161_000, 0)
	}
	/// Storage: `WeTEEWorker::BootPeers` (r:0 w:1)
	/// Proof: `WeTEEWorker::BootPeers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_boot_peers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_888_000 picoseconds.
		Weight::from_parts(9_609_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEWorker::Stage` (r:0 w:1)
	/// Proof: `WeTEEWorker::Stage` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_stage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_071_000 picoseconds.
		Weight::from_parts(6_627_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEWorker::CodeSigner` (r:0 w:1)
	/// Proof: `WeTEEWorker::CodeSigner` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEWorker::CodeSignature` (r:0 w:1)
	/// Proof: `WeTEEWorker::CodeSignature` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn upload_code() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 16_679_000 picoseconds.
		Weight::from_parts(17_199_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn work_stop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_723_000 picoseconds.
		Weight::from_parts(5_233_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn cluster_register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_962_000 picoseconds.
		Weight::from_parts(6_126_000, 0)
	}
	fn cluster_mortgage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_776_000 picoseconds.
		Weight::from_parts(5_025_000, 0)
	}
	fn cluster_unmortgage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_788_000 picoseconds.
		Weight::from_parts(5_059_000, 0)
	}
	fn work_proof_upload() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_155_000 picoseconds.
		Weight::from_parts(5_333_000, 0)
	}
	fn cluster_withdrawal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_980_000 picoseconds.
		Weight::from_parts(5_428_000, 0)
	}
	fn cluster_stop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_941_000 picoseconds.
		Weight::from_parts(5_266_000, 0)
	}
	fn cluster_report() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_211_000 picoseconds.
		Weight::from_parts(5_446_000, 0)
	}
	fn report_close() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_868_000 picoseconds.
		Weight::from_parts(5_161_000, 0)
	}
	/// Storage: `WeTEEWorker::BootPeers` (r:0 w:1)
	/// Proof: `WeTEEWorker::BootPeers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_boot_peers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_888_000 picoseconds.
		Weight::from_parts(9_609_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEWorker::Stage` (r:0 w:1)
	/// Proof: `WeTEEWorker::Stage` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_stage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_071_000 picoseconds.
		Weight::from_parts(6_627_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEWorker::CodeSigner` (r:0 w:1)
	/// Proof: `WeTEEWorker::CodeSigner` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEWorker::CodeSignature` (r:0 w:1)
	/// Proof: `WeTEEWorker::CodeSignature` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn upload_code() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 16_679_000 picoseconds.
		Weight::from_parts(17_199_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn work_stop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_723_000 picoseconds.
		Weight::from_parts(5_233_000, 0)
	}
}