[package]
authors = ["WeTEE DAO"]
edition = "2021"
name = "wetee-rpc"
publish = false
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "3.2.2"}
jsonrpsee = {version = "0.16.2", features = [
  "client-core",
  "server",
  "macros",
]}
sp-api = {workspace = true}
sp-blockchain = {workspace = true}
sp-core = {workspace = true}
sp-rpc = {workspace = true}
sp-runtime = {workspace = true}
sp-weights = {workspace = true}

wetee-primitives = {path = "../../primitives", default-features = false}
wetee-runtime-api = {path = "./runtime-api"}
