[package]
name = "wetee-rpc"
version = "1.0.0"
authors = ["dao-entrance"]
edition = "2021"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2" }
jsonrpsee = { version = "0.16.2", features = [
    "client-core",
    "server",
    "macros",
] }
sp-api = { git = "https://github.com/paritytech/substrate.git", "branch" = "polkadot-v1.0.0" }
sp-blockchain = { git = "https://github.com/paritytech/substrate.git", "branch" = "polkadot-v1.0.0" }
sp-core = { git = "https://github.com/paritytech/substrate.git", "branch" = "polkadot-v1.0.0" }
sp-rpc = { git = "https://github.com/paritytech/substrate.git", "branch" = "polkadot-v1.0.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", "branch" = "polkadot-v1.0.0" }
sp-weights = { git = "https://github.com/paritytech/substrate.git", "branch" = "polkadot-v1.0.0" }

wetee-runtime-api = { path = "./runtime-api" }
wetee-primitives = { path = "../../primitives", default-features = false }
