
//! Autogenerated weights for `wetee_treasury`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-09-03, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-treasury
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-treasury/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_treasury`.
pub trait WeightInfo {
	fn spend() -> Weight;
}

/// Weights for `wetee_treasury` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `WeTEEGov::Periods` (r:1 w:0)
	/// Proof: `WeTEEGov::Periods` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::DefaultPeriods` (r:1 w:0)
	/// Proof: `WeTEEGov::DefaultPeriods` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn spend() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `279`
		//  Estimated: `3744`
		// Minimum execution time: 25_427_000 picoseconds.
		Weight::from_parts(26_104_000, 3744)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `WeTEEGov::Periods` (r:1 w:0)
	/// Proof: `WeTEEGov::Periods` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::DefaultPeriods` (r:1 w:0)
	/// Proof: `WeTEEGov::DefaultPeriods` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn spend() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `279`
		//  Estimated: `3744`
		// Minimum execution time: 25_427_000 picoseconds.
		Weight::from_parts(26_104_000, 3744)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
}