
//! Autogenerated weights for `wetee_store`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-02-23, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-store
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-store/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_store`.
pub trait WeightInfo {
	fn register_app() -> Weight;
	fn unregister_app() -> Weight;
	fn review_app() -> Weight;
	fn init_mint() -> Weight;
	fn add_app_version() -> Weight;
}

/// Weights for `wetee_store` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn register_app() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_407_000 picoseconds.
		Weight::from_parts(5_811_000, 0)
	}
	fn unregister_app() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_696_000 picoseconds.
		Weight::from_parts(5_031_000, 0)
	}
	fn review_app() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_516_000 picoseconds.
		Weight::from_parts(4_648_000, 0)
	}
	/// Storage: `Asset::AssetSymbols` (r:1 w:1)
	/// Proof: `Asset::AssetSymbols` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Asset::AssetInfos` (r:1 w:1)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::TotalIssuance` (r:1 w:0)
	/// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn init_mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75`
		//  Estimated: `3540`
		// Minimum execution time: 35_706_000 picoseconds.
		Weight::from_parts(36_247_000, 3540)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn add_app_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_844_000 picoseconds.
		Weight::from_parts(5_051_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn register_app() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_407_000 picoseconds.
		Weight::from_parts(5_811_000, 0)
	}
	fn unregister_app() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_696_000 picoseconds.
		Weight::from_parts(5_031_000, 0)
	}
	fn review_app() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_516_000 picoseconds.
		Weight::from_parts(4_648_000, 0)
	}
	/// Storage: `Asset::AssetSymbols` (r:1 w:1)
	/// Proof: `Asset::AssetSymbols` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Asset::AssetInfos` (r:1 w:1)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::TotalIssuance` (r:1 w:0)
	/// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn init_mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `75`
		//  Estimated: `3540`
		// Minimum execution time: 35_706_000 picoseconds.
		Weight::from_parts(36_247_000, 3540)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn add_app_version() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_844_000 picoseconds.
		Weight::from_parts(5_051_000, 0)
	}
}