[package]
name = "tools-hash"
version = "3.0.0"
edition = "2018"

[dependencies]
hex = "0.4.0"
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", "branch" = "polkadot-v0.9.35" }

[features]
default = ["std"]
std = [
	# "sp-core/std",
]
