
//! Autogenerated weights for `wetee_assets`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-02-23, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-assets
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-assets/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_assets`.
pub trait WeightInfo {
	fn create_asset() -> Weight;
	fn delete_asset() -> Weight;
	fn burn() -> Weight;
	fn transfer() -> Weight;
	fn parachain_asset_register() -> Weight;
	fn set_chain_id() -> Weight;
	fn delete_parachain_for_asset() -> Weight;
	fn set_parachain_for_asset() -> Weight;
}

/// Weights for `wetee_assets` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Dao::NextDaoId` (r:1 w:1)
	/// Proof: `Dao::NextDaoId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Asset::AssetSymbols` (r:1 w:1)
	/// Proof: `Asset::AssetSymbols` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Asset::AssetInfos` (r:1 w:1)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::TotalIssuance` (r:1 w:1)
	/// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Tokens::Accounts` (r:1 w:1)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	fn create_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `3759`
		// Minimum execution time: 69_996_000 picoseconds.
		Weight::from_parts(70_837_000, 3759)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	fn delete_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_672_000 picoseconds.
		Weight::from_parts(5_086_000, 0)
	}
	/// Storage: `Asset::AssetInfos` (r:1 w:0)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159`
		//  Estimated: `3624`
		// Minimum execution time: 14_877_000 picoseconds.
		Weight::from_parts(15_033_000, 3624)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `Asset::AssetInfos` (r:1 w:0)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159`
		//  Estimated: `3624`
		// Minimum execution time: 15_095_000 picoseconds.
		Weight::from_parts(15_260_000, 3624)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	fn parachain_asset_register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_782_000 picoseconds.
		Weight::from_parts(6_104_000, 0)
	}
	fn set_chain_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_004_000 picoseconds.
		Weight::from_parts(5_147_000, 0)
	}
	fn delete_parachain_for_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_978_000 picoseconds.
		Weight::from_parts(5_152_000, 0)
	}
	fn set_parachain_for_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_093_000 picoseconds.
		Weight::from_parts(5_200_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Dao::NextDaoId` (r:1 w:1)
	/// Proof: `Dao::NextDaoId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Asset::AssetSymbols` (r:1 w:1)
	/// Proof: `Asset::AssetSymbols` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Asset::AssetInfos` (r:1 w:1)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::TotalIssuance` (r:1 w:1)
	/// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Tokens::Accounts` (r:1 w:1)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	fn create_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `294`
		//  Estimated: `3759`
		// Minimum execution time: 69_996_000 picoseconds.
		Weight::from_parts(70_837_000, 3759)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	fn delete_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_672_000 picoseconds.
		Weight::from_parts(5_086_000, 0)
	}
	/// Storage: `Asset::AssetInfos` (r:1 w:0)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159`
		//  Estimated: `3624`
		// Minimum execution time: 14_877_000 picoseconds.
		Weight::from_parts(15_033_000, 3624)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `Asset::AssetInfos` (r:1 w:0)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `159`
		//  Estimated: `3624`
		// Minimum execution time: 15_095_000 picoseconds.
		Weight::from_parts(15_260_000, 3624)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	fn parachain_asset_register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_782_000 picoseconds.
		Weight::from_parts(6_104_000, 0)
	}
	fn set_chain_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_004_000 picoseconds.
		Weight::from_parts(5_147_000, 0)
	}
	fn delete_parachain_for_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_978_000 picoseconds.
		Weight::from_parts(5_152_000, 0)
	}
	fn set_parachain_for_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_093_000 picoseconds.
		Weight::from_parts(5_200_000, 0)
	}
}