
//! Autogenerated weights for `wetee_assets`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-08-20, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-assets
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-assets/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_assets`.
pub trait WeightInfo {
	fn create_asset() -> Weight;
	fn set_existenial_deposit() -> Weight;
	fn set_metadata() -> Weight;
	fn burn() -> Weight;
	fn transfer() -> Weight;
}

/// Weights for `wetee_assets` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEAsset::DaoAssetsInfo` (r:1 w:0)
	/// Proof: `WeTEEAsset::DaoAssetsInfo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::TotalIssuance` (r:1 w:0)
	/// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Tokens::Accounts` (r:1 w:0)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	fn create_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `355`
		//  Estimated: `3820`
		// Minimum execution time: 79_250_000 picoseconds.
		Weight::from_parts(80_559_000, 3820)
			.saturating_add(T::DbWeight::get().reads(4_u64))
	}
	/// Storage: `WeTEEAsset::ExistentDeposits` (r:0 w:1)
	/// Proof: `WeTEEAsset::ExistentDeposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_existenial_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 15_522_000 picoseconds.
		Weight::from_parts(15_780_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEAsset::DaoAssetsInfo` (r:1 w:0)
	/// Proof: `WeTEEAsset::DaoAssetsInfo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `3681`
		// Minimum execution time: 21_495_000 picoseconds.
		Weight::from_parts(22_220_000, 3681)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEAsset::DaoAssetsInfo` (r:1 w:0)
	/// Proof: `WeTEEAsset::DaoAssetsInfo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `3681`
		// Minimum execution time: 21_655_000 picoseconds.
		Weight::from_parts(22_355_000, 3681)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEAsset::DaoAssetsInfo` (r:1 w:0)
	/// Proof: `WeTEEAsset::DaoAssetsInfo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `313`
		//  Estimated: `3778`
		// Minimum execution time: 28_048_000 picoseconds.
		Weight::from_parts(28_370_000, 3778)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEAsset::DaoAssetsInfo` (r:1 w:0)
	/// Proof: `WeTEEAsset::DaoAssetsInfo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tokens::TotalIssuance` (r:1 w:0)
	/// Proof: `Tokens::TotalIssuance` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `Tokens::Accounts` (r:1 w:0)
	/// Proof: `Tokens::Accounts` (`max_values`: None, `max_size`: Some(112), added: 2587, mode: `MaxEncodedLen`)
	fn create_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `355`
		//  Estimated: `3820`
		// Minimum execution time: 79_250_000 picoseconds.
		Weight::from_parts(80_559_000, 3820)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
	}
	/// Storage: `WeTEEAsset::ExistentDeposits` (r:0 w:1)
	/// Proof: `WeTEEAsset::ExistentDeposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_existenial_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 15_522_000 picoseconds.
		Weight::from_parts(15_780_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEAsset::DaoAssetsInfo` (r:1 w:0)
	/// Proof: `WeTEEAsset::DaoAssetsInfo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `3681`
		// Minimum execution time: 21_495_000 picoseconds.
		Weight::from_parts(22_220_000, 3681)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEAsset::DaoAssetsInfo` (r:1 w:0)
	/// Proof: `WeTEEAsset::DaoAssetsInfo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `216`
		//  Estimated: `3681`
		// Minimum execution time: 21_655_000 picoseconds.
		Weight::from_parts(22_355_000, 3681)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEAsset::DaoAssetsInfo` (r:1 w:0)
	/// Proof: `WeTEEAsset::DaoAssetsInfo` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `313`
		//  Estimated: `3778`
		// Minimum execution time: 28_048_000 picoseconds.
		Weight::from_parts(28_370_000, 3778)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
}