
//! Autogenerated weights for `wetee_gov`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-08-21, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-gov
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-gov/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_gov`.
pub trait WeightInfo {
	fn submit_proposal() -> Weight;
	fn set_periods() -> Weight;
	fn update_vote_model() -> Weight;
	fn set_max_pre_props() -> Weight;
	fn deposit_proposal() -> Weight;
	fn vote_for_prop() -> Weight;
	fn cancel_vote() -> Weight;
	fn run_proposal() -> Weight;
	fn unlock() -> Weight;
}

/// Weights for `wetee_gov` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `WeTEEGov::Periods` (r:1 w:0)
	/// Proof: `WeTEEGov::Periods` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Members` (r:1 w:0)
	/// Proof: `WeTEEOrg::Members` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::PrePropCount` (r:1 w:1)
	/// Proof: `WeTEEGov::PrePropCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::PreProps` (r:1 w:1)
	/// Proof: `WeTEEGov::PreProps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::MaxPreProps` (r:1 w:0)
	/// Proof: `WeTEEGov::MaxPreProps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `527`
		//  Estimated: `3992`
		// Minimum execution time: 60_523_000 picoseconds.
		Weight::from_parts(61_222_000, 3992)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `WeTEEGov::Periods` (r:0 w:1)
	/// Proof: `WeTEEGov::Periods` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_periods() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 16_264_000 picoseconds.
		Weight::from_parts(16_978_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEGov::VoteModel` (r:0 w:1)
	/// Proof: `WeTEEGov::VoteModel` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_vote_model() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 15_327_000 picoseconds.
		Weight::from_parts(15_596_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEGov::MaxPreProps` (r:0 w:1)
	/// Proof: `WeTEEGov::MaxPreProps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_max_pre_props() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 15_367_000 picoseconds.
		Weight::from_parts(15_815_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEGov::PreProps` (r:1 w:0)
	/// Proof: `WeTEEGov::PreProps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::Periods` (r:1 w:0)
	/// Proof: `WeTEEGov::Periods` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Members` (r:1 w:0)
	/// Proof: `WeTEEOrg::Members` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::PropCount` (r:1 w:1)
	/// Proof: `WeTEEGov::PropCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::DepositOf` (r:0 w:1)
	/// Proof: `WeTEEGov::DepositOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::Props` (r:0 w:1)
	/// Proof: `WeTEEGov::Props` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deposit_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `508`
		//  Estimated: `3973`
		// Minimum execution time: 53_093_000 picoseconds.
		Weight::from_parts(53_620_000, 3973)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `WeTEEGov::VotesOf` (r:1 w:0)
	/// Proof: `WeTEEGov::VotesOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::Props` (r:1 w:0)
	/// Proof: `WeTEEGov::Props` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn vote_for_prop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `3632`
		// Minimum execution time: 18_206_000 picoseconds.
		Weight::from_parts(18_448_000, 3632)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `WeTEEGov::Props` (r:1 w:0)
	/// Proof: `WeTEEGov::Props` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `3632`
		// Minimum execution time: 14_141_000 picoseconds.
		Weight::from_parts(14_482_000, 3632)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `WeTEEGov::Props` (r:1 w:0)
	/// Proof: `WeTEEGov::Props` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn run_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `3632`
		// Minimum execution time: 15_122_000 picoseconds.
		Weight::from_parts(15_457_000, 3632)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `WeTEEGov::ReserveOf` (r:1 w:1)
	/// Proof: `WeTEEGov::ReserveOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::VotesOf` (r:1 w:1)
	/// Proof: `WeTEEGov::VotesOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn unlock() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `3605`
		// Minimum execution time: 28_642_000 picoseconds.
		Weight::from_parts(28_857_000, 3605)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `WeTEEGov::Periods` (r:1 w:0)
	/// Proof: `WeTEEGov::Periods` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Members` (r:1 w:0)
	/// Proof: `WeTEEOrg::Members` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::PrePropCount` (r:1 w:1)
	/// Proof: `WeTEEGov::PrePropCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::PreProps` (r:1 w:1)
	/// Proof: `WeTEEGov::PreProps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::MaxPreProps` (r:1 w:0)
	/// Proof: `WeTEEGov::MaxPreProps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `527`
		//  Estimated: `3992`
		// Minimum execution time: 60_523_000 picoseconds.
		Weight::from_parts(61_222_000, 3992)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `WeTEEGov::Periods` (r:0 w:1)
	/// Proof: `WeTEEGov::Periods` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_periods() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 16_264_000 picoseconds.
		Weight::from_parts(16_978_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEGov::VoteModel` (r:0 w:1)
	/// Proof: `WeTEEGov::VoteModel` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_vote_model() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 15_327_000 picoseconds.
		Weight::from_parts(15_596_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEGov::MaxPreProps` (r:0 w:1)
	/// Proof: `WeTEEGov::MaxPreProps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_max_pre_props() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 15_367_000 picoseconds.
		Weight::from_parts(15_815_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEGov::PreProps` (r:1 w:0)
	/// Proof: `WeTEEGov::PreProps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::Periods` (r:1 w:0)
	/// Proof: `WeTEEGov::Periods` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Members` (r:1 w:0)
	/// Proof: `WeTEEOrg::Members` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::PropCount` (r:1 w:1)
	/// Proof: `WeTEEGov::PropCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::DepositOf` (r:0 w:1)
	/// Proof: `WeTEEGov::DepositOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::Props` (r:0 w:1)
	/// Proof: `WeTEEGov::Props` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deposit_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `508`
		//  Estimated: `3973`
		// Minimum execution time: 53_093_000 picoseconds.
		Weight::from_parts(53_620_000, 3973)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `WeTEEGov::VotesOf` (r:1 w:0)
	/// Proof: `WeTEEGov::VotesOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::Props` (r:1 w:0)
	/// Proof: `WeTEEGov::Props` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn vote_for_prop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `3632`
		// Minimum execution time: 18_206_000 picoseconds.
		Weight::from_parts(18_448_000, 3632)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `WeTEEGov::Props` (r:1 w:0)
	/// Proof: `WeTEEGov::Props` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `3632`
		// Minimum execution time: 14_141_000 picoseconds.
		Weight::from_parts(14_482_000, 3632)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `WeTEEGov::Props` (r:1 w:0)
	/// Proof: `WeTEEGov::Props` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn run_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `167`
		//  Estimated: `3632`
		// Minimum execution time: 15_122_000 picoseconds.
		Weight::from_parts(15_457_000, 3632)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `WeTEEGov::ReserveOf` (r:1 w:1)
	/// Proof: `WeTEEGov::ReserveOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEGov::VotesOf` (r:1 w:1)
	/// Proof: `WeTEEGov::VotesOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn unlock() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `3605`
		// Minimum execution time: 28_642_000 picoseconds.
		Weight::from_parts(28_857_000, 3605)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}