
//! Autogenerated weights for `wetee_dao`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-09-03, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-dao
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-dao/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_dao`.
pub trait WeightInfo {
	fn xxxx() -> Weight;
}

/// Weights for `wetee_dao` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `WeTEEOrg::NextDaoId` (r:1 w:1)
	/// Proof: `WeTEEOrg::NextDaoId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Members` (r:1 w:1)
	/// Proof: `WeTEEOrg::Members` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Guilds` (r:1 w:1)
	/// Proof: `WeTEEOrg::Guilds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::GuildMembers` (r:1 w:1)
	/// Proof: `WeTEEOrg::GuildMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Daos` (r:0 w:1)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::Account` (r:0 w:1)
	/// Proof: `WeTEESudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn xxxx() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3469`
		// Minimum execution time: 54_956_000 picoseconds.
		Weight::from_parts(55_720_000, 3469)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `WeTEEOrg::NextDaoId` (r:1 w:1)
	/// Proof: `WeTEEOrg::NextDaoId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Members` (r:1 w:1)
	/// Proof: `WeTEEOrg::Members` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Guilds` (r:1 w:1)
	/// Proof: `WeTEEOrg::Guilds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::GuildMembers` (r:1 w:1)
	/// Proof: `WeTEEOrg::GuildMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Daos` (r:0 w:1)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::Account` (r:0 w:1)
	/// Proof: `WeTEESudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn xxxx() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3469`
		// Minimum execution time: 54_956_000 picoseconds.
		Weight::from_parts(55_720_000, 3469)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
}