
//! Autogenerated weights for `wetee_fairlanch`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-02-23, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-fairlanch
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-fairlanch/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_fairlanch`.
pub trait WeightInfo {
	fn v_staking() -> Weight;
	fn v_unstaking() -> Weight;
	fn set_economics() -> Weight;
	fn register_vtoken() -> Weight;
	fn set_vtoken_rate() -> Weight;
	fn delete_economics() -> Weight;
	fn v_staking_cancel() -> Weight;
	fn set_epoch() -> Weight;
}

/// Weights for `wetee_fairlanch` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn v_staking() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_621_000 picoseconds.
		Weight::from_parts(4_864_000, 0)
	}
	fn v_unstaking() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_775_000 picoseconds.
		Weight::from_parts(5_007_000, 0)
	}
	/// Storage: `Asset::AssetInfos` (r:1 w:0)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_economics() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `3534`
		// Minimum execution time: 12_256_000 picoseconds.
		Weight::from_parts(12_918_000, 3534)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `Asset::AssetInfos` (r:1 w:0)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_vtoken() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `3534`
		// Minimum execution time: 12_377_000 picoseconds.
		Weight::from_parts(12_926_000, 3534)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `Fairlanch::Vtoken2token` (r:1 w:0)
	/// Proof: `Fairlanch::Vtoken2token` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_vtoken_rate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `113`
		//  Estimated: `3578`
		// Minimum execution time: 11_258_000 picoseconds.
		Weight::from_parts(11_529_000, 3578)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `Asset::AssetInfos` (r:1 w:0)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delete_economics() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `3534`
		// Minimum execution time: 12_450_000 picoseconds.
		Weight::from_parts(12_753_000, 3534)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	fn v_staking_cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_818_000 picoseconds.
		Weight::from_parts(4_927_000, 0)
	}
	/// Storage: `Fairlanch::BlockReward` (r:0 w:1)
	/// Proof: `Fairlanch::BlockReward` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_358_000 picoseconds.
		Weight::from_parts(7_851_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn v_staking() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_621_000 picoseconds.
		Weight::from_parts(4_864_000, 0)
	}
	fn v_unstaking() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_775_000 picoseconds.
		Weight::from_parts(5_007_000, 0)
	}
	/// Storage: `Asset::AssetInfos` (r:1 w:0)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_economics() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `3534`
		// Minimum execution time: 12_256_000 picoseconds.
		Weight::from_parts(12_918_000, 3534)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `Asset::AssetInfos` (r:1 w:0)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_vtoken() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `3534`
		// Minimum execution time: 12_377_000 picoseconds.
		Weight::from_parts(12_926_000, 3534)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `Fairlanch::Vtoken2token` (r:1 w:0)
	/// Proof: `Fairlanch::Vtoken2token` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_vtoken_rate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `113`
		//  Estimated: `3578`
		// Minimum execution time: 11_258_000 picoseconds.
		Weight::from_parts(11_529_000, 3578)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `Asset::AssetInfos` (r:1 w:0)
	/// Proof: `Asset::AssetInfos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delete_economics() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `3534`
		// Minimum execution time: 12_450_000 picoseconds.
		Weight::from_parts(12_753_000, 3534)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	fn v_staking_cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_818_000 picoseconds.
		Weight::from_parts(4_927_000, 0)
	}
	/// Storage: `Fairlanch::BlockReward` (r:0 w:1)
	/// Proof: `Fairlanch::BlockReward` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_epoch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_358_000 picoseconds.
		Weight::from_parts(7_851_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}