[package]
authors = ["dao-entrance"]
edition = "2021"
name = "wetee-sudo"
publish = false
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "3.4.0", default-features = false, features = [
  "derive",
]}
frame-benchmarking = {workspace = true}
frame-support = {workspace = true}
frame-system = {workspace = true}
pallet-balances = {workspace = true}
scale-info = {version = "2.10.0", default-features = false, features = [
  "derive",
]}
sp-runtime = {workspace = true}
sp-std = {workspace = true}

wetee-org = {path = "../wetee-org", package = "wetee-org", default-features = false}
wetee-primitives = {path = "../../primitives", package = "wetee-primitives", default-features = false}

[dev-dependencies]
sp-core = {workspace = true}
sp-io = {workspace = true}
sp-runtime = {workspace = true}

[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
std = [
  "codec/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
  "scale-info/std",
  "wetee-primitives/std",
  "wetee-org/std",
]
try-runtime = ["frame-support/try-runtime"]
