
//! Autogenerated weights for `wetee_org`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-08-20, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-org
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-org/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_org`.
pub trait WeightInfo {
	fn create_dao() -> Weight;
	fn update_dao() -> Weight;
	fn create_roadmap_task() -> Weight;
	fn update_roadmap_task() -> Weight;
	fn create_app() -> Weight;
	fn update_app_status() -> Weight;
	fn org_integrate_app() -> Weight;
	fn update_org_app_status() -> Weight;
}

/// Weights for `wetee_org` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `WeTEEOrg::NextDaoId` (r:1 w:1)
	/// Proof: `WeTEEOrg::NextDaoId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Members` (r:1 w:1)
	/// Proof: `WeTEEOrg::Members` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Guilds` (r:1 w:1)
	/// Proof: `WeTEEOrg::Guilds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::GuildMembers` (r:1 w:1)
	/// Proof: `WeTEEOrg::GuildMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Daos` (r:0 w:1)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::Account` (r:0 w:1)
	/// Proof: `WeTEESudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_dao() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3469`
		// Minimum execution time: 53_708_000 picoseconds.
		Weight::from_parts(55_033_000, 3469)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:1)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_dao() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `271`
		//  Estimated: `3736`
		// Minimum execution time: 33_622_000 picoseconds.
		Weight::from_parts(34_459_000, 3736)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::NextTaskId` (r:1 w:1)
	/// Proof: `WeTEEOrg::NextTaskId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::RoadMaps` (r:1 w:1)
	/// Proof: `WeTEEOrg::RoadMaps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_roadmap_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `296`
		//  Estimated: `3761`
		// Minimum execution time: 38_533_000 picoseconds.
		Weight::from_parts(39_335_000, 3761)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::RoadMaps` (r:1 w:1)
	/// Proof: `WeTEEOrg::RoadMaps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_roadmap_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `423`
		//  Estimated: `3888`
		// Minimum execution time: 40_832_000 picoseconds.
		Weight::from_parts(41_242_000, 3888)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::NextAppId` (r:1 w:1)
	/// Proof: `WeTEEOrg::NextAppId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::AppHubs` (r:0 w:1)
	/// Proof: `WeTEEOrg::AppHubs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_app() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `307`
		//  Estimated: `3772`
		// Minimum execution time: 33_502_000 picoseconds.
		Weight::from_parts(33_940_000, 3772)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::AppHubs` (r:1 w:1)
	/// Proof: `WeTEEOrg::AppHubs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_app_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `373`
		//  Estimated: `3838`
		// Minimum execution time: 36_387_000 picoseconds.
		Weight::from_parts(36_935_000, 3838)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::AppHubs` (r:1 w:0)
	/// Proof: `WeTEEOrg::AppHubs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::OrgApps` (r:1 w:1)
	/// Proof: `WeTEEOrg::OrgApps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn org_integrate_app() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `373`
		//  Estimated: `3838`
		// Minimum execution time: 39_771_000 picoseconds.
		Weight::from_parts(40_528_000, 3838)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::OrgApps` (r:1 w:1)
	/// Proof: `WeTEEOrg::OrgApps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_org_app_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `393`
		//  Estimated: `3858`
		// Minimum execution time: 36_834_000 picoseconds.
		Weight::from_parts(37_471_000, 3858)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `WeTEEOrg::NextDaoId` (r:1 w:1)
	/// Proof: `WeTEEOrg::NextDaoId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Members` (r:1 w:1)
	/// Proof: `WeTEEOrg::Members` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Guilds` (r:1 w:1)
	/// Proof: `WeTEEOrg::Guilds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::GuildMembers` (r:1 w:1)
	/// Proof: `WeTEEOrg::GuildMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Daos` (r:0 w:1)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::Account` (r:0 w:1)
	/// Proof: `WeTEESudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_dao() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3469`
		// Minimum execution time: 53_708_000 picoseconds.
		Weight::from_parts(55_033_000, 3469)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:1)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_dao() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `271`
		//  Estimated: `3736`
		// Minimum execution time: 33_622_000 picoseconds.
		Weight::from_parts(34_459_000, 3736)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::NextTaskId` (r:1 w:1)
	/// Proof: `WeTEEOrg::NextTaskId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::RoadMaps` (r:1 w:1)
	/// Proof: `WeTEEOrg::RoadMaps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_roadmap_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `296`
		//  Estimated: `3761`
		// Minimum execution time: 38_533_000 picoseconds.
		Weight::from_parts(39_335_000, 3761)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::RoadMaps` (r:1 w:1)
	/// Proof: `WeTEEOrg::RoadMaps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_roadmap_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `423`
		//  Estimated: `3888`
		// Minimum execution time: 40_832_000 picoseconds.
		Weight::from_parts(41_242_000, 3888)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::NextAppId` (r:1 w:1)
	/// Proof: `WeTEEOrg::NextAppId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::AppHubs` (r:0 w:1)
	/// Proof: `WeTEEOrg::AppHubs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_app() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `307`
		//  Estimated: `3772`
		// Minimum execution time: 33_502_000 picoseconds.
		Weight::from_parts(33_940_000, 3772)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::AppHubs` (r:1 w:1)
	/// Proof: `WeTEEOrg::AppHubs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_app_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `373`
		//  Estimated: `3838`
		// Minimum execution time: 36_387_000 picoseconds.
		Weight::from_parts(36_935_000, 3838)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::AppHubs` (r:1 w:0)
	/// Proof: `WeTEEOrg::AppHubs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::OrgApps` (r:1 w:1)
	/// Proof: `WeTEEOrg::OrgApps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn org_integrate_app() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `373`
		//  Estimated: `3838`
		// Minimum execution time: 39_771_000 picoseconds.
		Weight::from_parts(40_528_000, 3838)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::OrgApps` (r:1 w:1)
	/// Proof: `WeTEEOrg::OrgApps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_org_app_status() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `393`
		//  Estimated: `3858`
		// Minimum execution time: 36_834_000 picoseconds.
		Weight::from_parts(37_471_000, 3858)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}