[package]
authors = ["WeTEE DAO"]
edition = "2021"
name = "wetee-gov"
publish = false
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-benchmarking = {workspace = true}
frame-support = {workspace = true}
frame-system = {workspace = true}
log = "0.4.17"
pallet-balances = {workspace = true}
parity-scale-codec = {workspace = true, default-features = false, features = [
  "derive",
]}
scale-info = {workspace = true, default-features = false, features = [
  "derive",
]}
serde = {workspace = true, optional = true}
sp-runtime = {workspace = true}
sp-std = {workspace = true}

orml-tokens = {workspace = true}
orml-traits = {workspace = true}
# orml-traits = { default-features = false, path = "../../../../open-runtime-module-library/traits" }
# orml-tokens = { default-features = false, path = "../../../../open-runtime-module-library/tokens" }

wetee-assets = {path = "../wetee-assets", package = "wetee-assets", default-features = false}
wetee-org = {path = "../wetee-org", package = "wetee-org", default-features = false}
wetee-primitives = {path = "../../primitives", package = "wetee-primitives", default-features = false}
wetee-sudo = {path = "../wetee-sudo", package = "wetee-sudo", default-features = false}

[dev-dependencies]
sp-core = {workspace = true}
sp-io = {workspace = true}
sp-runtime = {workspace = true}

[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
std = [
  "parity-scale-codec/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
  "scale-info/std",
  "pallet-balances/std",
  "wetee-primitives/std",
  "wetee-org/std",
  "wetee-sudo/std",
  "wetee-assets/std",
]
try-runtime = ["frame-support/try-runtime"]
