
//! Autogenerated weights for `wetee_dsecret`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-09-03, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-dsecret
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-dsecret/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_dsecret`.
pub trait WeightInfo {
	fn register_node() -> Weight;
	fn upload_code() -> Weight;
	fn upload_cluster_proof() -> Weight;
	fn work_launch() -> Weight;
	fn set_node_pub_server() -> Weight;
}

/// Weights for `wetee_dsecret` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `WeTEEDsecret::NextNodeId` (r:1 w:1)
	/// Proof: `WeTEEDsecret::NextNodeId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEDsecret::Nodes` (r:0 w:1)
	/// Proof: `WeTEEDsecret::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1594`
		// Minimum execution time: 20_789_000 picoseconds.
		Weight::from_parts(22_112_000, 1594)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `WeTEEDsecret::CodeSigner` (r:0 w:1)
	/// Proof: `WeTEEDsecret::CodeSigner` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEDsecret::CodeSignature` (r:0 w:1)
	/// Proof: `WeTEEDsecret::CodeSignature` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn upload_code() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 16_462_000 picoseconds.
		Weight::from_parts(17_017_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn upload_cluster_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_502_000 picoseconds.
		Weight::from_parts(11_745_000, 0)
	}
	fn work_launch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_315_000 picoseconds.
		Weight::from_parts(6_559_000, 0)
	}
	fn set_node_pub_server() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_804_000 picoseconds.
		Weight::from_parts(5_989_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `WeTEEDsecret::NextNodeId` (r:1 w:1)
	/// Proof: `WeTEEDsecret::NextNodeId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEDsecret::Nodes` (r:0 w:1)
	/// Proof: `WeTEEDsecret::Nodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1594`
		// Minimum execution time: 20_789_000 picoseconds.
		Weight::from_parts(22_112_000, 1594)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `WeTEEDsecret::CodeSigner` (r:0 w:1)
	/// Proof: `WeTEEDsecret::CodeSigner` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEDsecret::CodeSignature` (r:0 w:1)
	/// Proof: `WeTEEDsecret::CodeSignature` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn upload_code() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 16_462_000 picoseconds.
		Weight::from_parts(17_017_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn upload_cluster_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_502_000 picoseconds.
		Weight::from_parts(11_745_000, 0)
	}
	fn work_launch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_315_000 picoseconds.
		Weight::from_parts(6_559_000, 0)
	}
	fn set_node_pub_server() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_804_000 picoseconds.
		Weight::from_parts(5_989_000, 0)
	}
}