[package]
authors = ["WeTEE DAO"]
edition = "2021"
name = "wetee-runtime-api"
publish = false
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, default-features = false, features = [
  "derive",
] }
sp-api = {workspace = true}
sp-runtime = {workspace = true}
wetee-primitives = {path = "../../../primitives", default-features = false}

[features]
default = ["std"]
std = ["parity-scale-codec/std", "wetee-primitives/std", "sp-api/std", "sp-runtime/std"]
