[package]
authors = ["dao-entrance"]
edition = "2021"
name = "wetee-runtime-api"
publish = false
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "3.4.0", default-features = false, features = [
  "derive",
]}
sp-api = {workspace = true}
sp-runtime = {workspace = true}
wetee-primitives = {path = "../../../primitives", default-features = false}

[features]
default = ["std"]
std = ["codec/std", "wetee-primitives/std", "sp-api/std", "sp-runtime/std"]
