
//! Autogenerated weights for `wetee_guild`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-08-21, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-guild
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-guild/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_guild`.
pub trait WeightInfo {
	fn guild_join() -> Weight;
	fn create_guild() -> Weight;
}

/// Weights for `wetee_guild` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `WeTEEOrg::Guilds` (r:1 w:0)
	/// Proof: `WeTEEOrg::Guilds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::GuildMembers` (r:1 w:1)
	/// Proof: `WeTEEOrg::GuildMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn guild_join() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `337`
		//  Estimated: `3802`
		// Minimum execution time: 47_131_000 picoseconds.
		Weight::from_parts(48_727_000, 3802)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Guilds` (r:1 w:1)
	/// Proof: `WeTEEOrg::Guilds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::GuildMembers` (r:1 w:1)
	/// Proof: `WeTEEOrg::GuildMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_guild() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `334`
		//  Estimated: `3799`
		// Minimum execution time: 41_595_000 picoseconds.
		Weight::from_parts(42_248_000, 3799)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `WeTEEOrg::Guilds` (r:1 w:0)
	/// Proof: `WeTEEOrg::Guilds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::GuildMembers` (r:1 w:1)
	/// Proof: `WeTEEOrg::GuildMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn guild_join() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `337`
		//  Estimated: `3802`
		// Minimum execution time: 47_131_000 picoseconds.
		Weight::from_parts(48_727_000, 3802)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Guilds` (r:1 w:1)
	/// Proof: `WeTEEOrg::Guilds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::GuildMembers` (r:1 w:1)
	/// Proof: `WeTEEOrg::GuildMembers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_guild() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `334`
		//  Estimated: `3799`
		// Minimum execution time: 41_595_000 picoseconds.
		Weight::from_parts(42_248_000, 3799)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}