[package]
authors = ["[your_name] <[your_email]>"]
edition = "2021"
name = "example"
version = "0.1.0"

[dependencies]
ink = {version = "5.0.0", default-features = false}

[dev-dependencies]
ink_e2e = {version = "5.0.0"}
scale-info = {version = "2.10.0", default-features = false, features = [
  "derive",
  "serde",
]}

[lib]
path = "lib.rs"

[features]
default = ["std"]
e2e-tests = []
ink-as-dependency = []
std = [
  "ink/std",
]
