[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
name = "wetee-tee-bridge"
publish = false
repository.workspace = true
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-benchmarking = {workspace = true}
frame-support = {workspace = true}
frame-system = {workspace = true}
pallet-balances = {workspace = true}
parity-scale-codec = {workspace = true, default-features = false, features = [
  "derive",
]}
scale-info = {workspace = true, default-features = false, features = [
  "derive",
]}
sp-runtime = {workspace = true}
sp-std = {workspace = true}

wetee-org = {path = "../wetee-org", package = "wetee-org", default-features = false}

[dev-dependencies]
sp-core = {workspace = true}
sp-io = {workspace = true}
sp-runtime = {workspace = true}

[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
std = [
  "parity-scale-codec/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
  "scale-info/std",
  "wetee-org/std",
]
try-runtime = ["frame-support/try-runtime"]
