[package]
authors = ["WeTEE DAO"]
edition = "2021"
name = "wetee-worker"
publish = false
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, default-features = false, features = [
  "derive",
] }
frame-benchmarking = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
log = { workspace = true }
pallet-balances = { workspace = true }
scale-info = { workspace = true, default-features = false, features = [
  "derive",
] }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

orml-tokens = { workspace = true }
orml-traits = { workspace = true }
pallet-insecure-randomness-collective-flip = { workspace = true }

wetee-app = { path = "../wetee-app", package = "wetee-app", default-features = false }
wetee-assets = { path = "../wetee-assets", package = "wetee-assets", default-features = false }
wetee-org = { path = "../wetee-org", package = "wetee-org", default-features = false }
wetee-primitives = { path = "../../primitives", package = "wetee-primitives", default-features = false }
wetee-task = { path = "../wetee-task", package = "wetee-task", default-features = false }

[dev-dependencies]
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
std = [
  "parity-scale-codec/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
  "scale-info/std",
  "pallet-insecure-randomness-collective-flip/std",
  "pallet-balances/std",
  "wetee-primitives/std",
  "wetee-org/std",
  "wetee-assets/std",
  "wetee-app/std",
  "wetee-task/std",
]
try-runtime = ["frame-support/try-runtime"]
