[package]
authors = ["WeTEE DAO"]
edition = "2021"
name = "wetee-project"
publish = false
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "3.4.0", default-features = false, features = [
  "derive",
]}
frame-benchmarking = {default-features = false, optional = true, git = "https://github.com/paritytech/polkadot-sdk.git", "branch" = "release-polkadot-v1.1.0"}
frame-support = {default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", "branch" = "release-polkadot-v1.1.0"}
frame-system = {default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", "branch" = "release-polkadot-v1.1.0"}
pallet-balances = {git = 'https://github.com/paritytech/polkadot-sdk.git', branch = 'release-polkadot-v1.1.0', default-features = false}
scale-info = {version = "2.10.0", default-features = false, features = [
  "derive",
]}
serde = {version = "1.0.193", default-features = false, features = ["alloc", "derive"]}
sp-core = {default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", "branch" = "release-polkadot-v1.1.0"}
sp-io = {default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", "branch" = "release-polkadot-v1.1.0"}
sp-runtime = {default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", "branch" = "release-polkadot-v1.1.0"}
sp-std = {git = 'https://github.com/paritytech/polkadot-sdk.git', branch = 'release-polkadot-v1.1.0', default-features = false}

orml-tokens = {default-features = false, git = "https://github.com/open-web3-stack/open-runtime-module-library.git", branch = "polkadot-v1.1.0"}
orml-traits = {default-features = false, git = "https://github.com/open-web3-stack/open-runtime-module-library.git", branch = "polkadot-v1.1.0"}
# orml-traits = { default-features = false, path = "../../../../open-runtime-module-library/traits" }
# orml-tokens = { default-features = false, path = "../../../../open-runtime-module-library/tokens" }

wetee-assets = {path = "../wetee-assets", package = "wetee-assets", default-features = false}
wetee-gov = {path = "../wetee-gov", package = "wetee-gov", default-features = false}
wetee-org = {path = "../wetee-org", package = "wetee-org", default-features = false}
wetee-primitives = {path = "../../primitives", package = "wetee-primitives", default-features = false}
wetee-sudo = {path = "../wetee-sudo", package = "wetee-sudo", default-features = false}

[dev-dependencies]
# sp-runtime = {    default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", "branch" = "release-polkadot-v1.1.0" }

[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
std = [
  "codec/std",
  "frame-benchmarking?/std",
  "frame-support/std",
  "frame-system/std",
  "scale-info/std",
  "pallet-balances/std",
  "orml-traits/std",
  "orml-tokens/std",
  "wetee-primitives/std",
  "wetee-org/std",
  "wetee-sudo/std",
  "wetee-gov/std",
  "wetee-assets/std",
]
try-runtime = ["frame-support/try-runtime"]
