[package]
authors = ["dao-entrance"]
edition = "2021"
name = "wetee-guild"
publish = false
version = "1.0.0"

[package.metadata.docs.rs]
log = "0.4.17"
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "3.4.0", default-features = false, features = [
  "derive",
]}
frame-benchmarking = {workspace = true}
frame-support = {workspace = true}
frame-system = {workspace = true}
log = "0.4.17"
pallet-balances = {workspace = true}
scale-info = {version = "2.10.0", default-features = false, features = [
  "derive",
]}
serde = {version = "1.0.193", default-features = false, features = ["alloc", "derive"]}
sp-core = {workspace = true}
sp-io = {workspace = true}
sp-runtime = {workspace = true}
sp-std = {workspace = true}

orml-tokens = {workspace = true}
orml-traits = {workspace = true}
# orml-traits = { default-features = false, path = "../../../../open-runtime-module-library/traits" }
# orml-tokens = { default-features = false, path = "../../../../open-runtime-module-library/tokens" }

wetee-assets = {path = "../wetee-assets", package = "wetee-assets", default-features = false}
wetee-gov = {path = "../wetee-gov", package = "wetee-gov", default-features = false}
wetee-org = {path = "../wetee-org", package = "wetee-org", default-features = false}
wetee-primitives = {path = "../../primitives", package = "wetee-primitives", default-features = false}
wetee-sudo = {path = "../wetee-sudo", package = "wetee-sudo", default-features = false}

[dev-dependencies]
sp-runtime = {workspace = true}

[features]
default = ["std"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
std = [
  "codec/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
  "scale-info/std",
  "pallet-balances/std",
  "orml-traits/std",
  "orml-tokens/std",
  "wetee-primitives/std",
  "wetee-org/std",
  "wetee-sudo/std",
  "wetee-gov/std",
  "wetee-assets/std",
]
try-runtime = ["frame-support/try-runtime"]
