[package]
authors = ["wetee"]
build = "build.rs"
edition = "2021"
license = "Unlicense"
name = "wetee-node"
publish = false
version = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "wetee-node"

[dependencies]
clap = {workspace = true, features = ["derive"]}
futures = {workspace = true, features = ["thread-pool"]}

frame-system = {workspace = true}
pallet-transaction-payment = {workspace = true}
sc-cli = {workspace = true}
sc-client-api = {workspace = true}
sc-consensus = {workspace = true}
sc-consensus-aura = {workspace = true}
sc-consensus-grandpa = {workspace = true}
sc-executor = {workspace = true}
sc-network = {workspace = true}
sc-offchain = {workspace = true}
sc-service = {workspace = true}
sc-telemetry = {workspace = true}
sc-transaction-pool = {workspace = true}
sc-transaction-pool-api = {workspace = true}
sp-consensus-aura = {workspace = true}
sp-consensus-grandpa = {workspace = true}
sp-core = {workspace = true}
sp-inherents = {workspace = true}
sp-io = {workspace = true}
sp-keyring = {workspace = true}
sp-runtime = {workspace = true}
sp-timestamp = {workspace = true}

# These dependencies are used for the node template's RPCs
jsonrpsee = {workspace = true, features = ["server"]}
pallet-transaction-payment-rpc = {workspace = true}
sc-basic-authorship = {workspace = true}
sc-rpc-api = {workspace = true}
sp-api = {workspace = true}
sp-block-builder = {workspace = true}
sp-blockchain = {workspace = true}
substrate-frame-rpc-system = {workspace = true}

# These dependencies are used for runtime benchmarking
frame-benchmarking = {workspace = true}
frame-benchmarking-cli = {workspace = true}

# Local Dependencies
wetee-rpc = {path = "../../pallets/wetee-rpc"}
wetee-runtime = {path = "../runtime"}

# CLI-specific dependencies
try-runtime-cli = {optional = true, workspace = true}

[build-dependencies]
substrate-build-script-utils = {workspace = true}

[features]
default = []
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = [
  "wetee-runtime/runtime-benchmarks",
  "frame-benchmarking/runtime-benchmarks",
  "frame-benchmarking-cli/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["wetee-runtime/try-runtime", "try-runtime-cli/try-runtime"]
