[package]
authors.workspace = true
description = "A solochain node template built with Substrate, part of Polkadot Sdk."
edition.workspace = true
homepage.workspace = true
license = "MIT-0"
name = "wetee-node"
publish = false
repository.workspace = true
version = "0.0.0"

build = "build.rs"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = {version = "4.5.3", features = ["derive"]}
futures = {version = "0.3.30", features = ["thread-pool"]}
jsonrpsee = {version = "0.22", features = ["server"]}
serde_json = {version = "1.0.114", default-features = true}

# substrate client
sc-basic-authorship = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-cli = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-client-api = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-consensus = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-consensus-aura = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-consensus-grandpa = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-executor = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-network = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-offchain = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-rpc-api = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-service = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-telemetry = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-transaction-pool = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sc-transaction-pool-api = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sp-consensus-aura = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sp-consensus-grandpa = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sp-core = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}

# substrate primitives
sp-api = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sp-block-builder = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sp-blockchain = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sp-inherents = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sp-io = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sp-keyring = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sp-runtime = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
sp-timestamp = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}

# frame and pallets
frame-system = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
pallet-transaction-payment = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0", default-features = false}
pallet-transaction-payment-rpc = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}
substrate-frame-rpc-system = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}

# These dependencies are used for runtime benchmarking
frame-benchmarking-cli = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}

# Local Dependencies
wetee-runtime = {path = "../runtime"}

# CLI-specific dependencies
try-runtime-cli = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0", optional = true}

[build-dependencies]
substrate-build-script-utils = {git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0"}

[features]
default = []
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = [
  "frame-benchmarking-cli/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "sc-service/runtime-benchmarks",
  "wetee-runtime/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = [
  "frame-system/try-runtime",
  "pallet-transaction-payment/try-runtime",
  "wetee-runtime/try-runtime",
  "sp-runtime/try-runtime",
  "try-runtime-cli/try-runtime",
]
