[package]
authors.workspace = true
description = "A solochain node template built with Substrate, part of Polkadot Sdk."
edition.workspace = true
homepage.workspace = true
license = "MIT-0"
name = "wetee-node"
publish = false
repository.workspace = true
version = "0.0.0"

build = "build.rs"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = {version = "4.5.3", features = ["derive"]}
futures = {version = "0.3.30", features = ["thread-pool"]}
jsonrpsee = {version = "0.22", features = ["server"]}
serde_json = {version = "1.0.114", default-features = true}

# substrate client
sc-basic-authorship = {workspace = true}
sc-cli = {workspace = true}
sc-client-api = {workspace = true}
sc-consensus = {workspace = true}
sc-consensus-aura = {workspace = true}
sc-consensus-grandpa = {workspace = true}
sc-executor = {workspace = true}
sc-network = {workspace = true}
sc-offchain = {workspace = true}
sc-rpc-api = {workspace = true}
sc-service = {workspace = true}
sc-telemetry = {workspace = true}
sc-transaction-pool = {workspace = true}
sc-transaction-pool-api = {workspace = true}
sp-consensus-aura = {workspace = true}
sp-consensus-grandpa = {workspace = true}
sp-core = {workspace = true}

# substrate primitives
sp-api = {workspace = true}
sp-block-builder = {workspace = true}
sp-blockchain = {workspace = true}
sp-inherents = {workspace = true}
sp-io = {workspace = true}
sp-keyring = {workspace = true}
sp-runtime = {workspace = true}
sp-timestamp = {workspace = true}

# frame and pallets
frame-system = {workspace = true}
pallet-transaction-payment = {workspace = true, default-features = false}
pallet-transaction-payment-rpc = {workspace = true}
substrate-frame-rpc-system = {workspace = true}

# These dependencies are used for runtime benchmarking
frame-benchmarking-cli = {workspace = true}

# Local Dependencies
wetee-runtime = {path = "../runtime"}

[build-dependencies]
substrate-build-script-utils = {workspace = true}

[features]
default = []
# Dependencies that are only required if runtime benchmarking should be build.
runtime-benchmarks = [
  "frame-benchmarking-cli/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "sc-service/runtime-benchmarks",
  "wetee-runtime/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = [
  "frame-system/try-runtime",
  "pallet-transaction-payment/try-runtime",
  "wetee-runtime/try-runtime",
  "sp-runtime/try-runtime",
]
