[package]
authors = ["WeTEE DAO"]
edition = "2021"
license = "Apache-2.0"
name = "wetee-primitives"
version = "1.0.0"

[dependencies]
codec = {package = "parity-scale-codec", version = "3.4.0", default-features = false, features = [
  "derive",
]}
scale-info = {version = "2.10.0", default-features = false, features = [
  "derive",
]}

frame-support = {workspace = true}
sp-runtime = {workspace = true}
sp-std = {workspace = true}

[features]
default = ["std"]
runtime-benchmarks = []
std = [
  "codec/std",
  "frame-support/std",
  "scale-info/std",
  "sp-runtime/std",
  "sp-std/std",
]
