[package]
authors = ["WeTEE DAO"]
edition = "2021"
license = "Apache-2.0"
name = "wetee-primitives"
version = "1.0.0"

[dependencies]
parity-scale-codec = { workspace = true, default-features = false, features = [
  "derive",
] }
scale-info = { workspace = true, default-features = false, features = [
  "derive",
] }

frame-support = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = []
std = [
  "parity-scale-codec/std",
  "frame-support/std",
  "scale-info/std",
  "sp-runtime/std",
  "sp-std/std",
]
