[package]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
name = "wetee-runtime"
publish = false
repository.workspace = true
version = "1.0.0"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = {package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
  "derive",
]}
log = {workspace = true}
scale-info = {version = "2.10.0", default-features = false, features = [
  "derive",
  "serde",
]}

# frame
frame-executive = {workspace = true, default-features = false}
frame-support = {workspace = true, default-features = false, features = ["experimental"]}
frame-system = {workspace = true, default-features = false}
frame-try-runtime = {workspace = true, default-features = false, optional = true}

# frame pallets
pallet-aura = {workspace = true, default-features = false}
pallet-balances = {workspace = true, default-features = false}
pallet-grandpa = {workspace = true, default-features = false}
pallet-sudo = {workspace = true, default-features = false}
pallet-timestamp = {workspace = true, default-features = false}
pallet-transaction-payment = {workspace = true, default-features = false}

# primitives
sp-api = {workspace = true, default-features = false}
sp-block-builder = {workspace = true, default-features = false}
sp-consensus-aura = {workspace = true, default-features = false, features = [
  "serde",
]}
sp-consensus-grandpa = {workspace = true, default-features = false, features = [
  "serde",
]}
sp-core = {workspace = true, default-features = false, features = [
  "serde",
]}
sp-genesis-builder = {default-features = false, workspace = true}
sp-inherents = {workspace = true, default-features = false}
sp-offchain = {workspace = true, default-features = false}
sp-runtime = {workspace = true, default-features = false, features = [
  "serde",
]}
sp-session = {workspace = true, default-features = false}
sp-std = {workspace = true, default-features = false}
sp-storage = {workspace = true, default-features = false}
sp-transaction-pool = {workspace = true, default-features = false}
sp-version = {workspace = true, default-features = false, features = [
  "serde",
]}

# RPC related
frame-system-rpc-runtime-api = {workspace = true, default-features = false}
pallet-transaction-payment-rpc-runtime-api = {workspace = true, default-features = false}

# Used for runtime benchmarking
frame-benchmarking = {workspace = true, default-features = false, optional = true}
frame-system-benchmarking = {workspace = true, default-features = false, optional = true}

# Local Dependencies
orml-tokens = {workspace = true}
orml-traits = {workspace = true}
pallet-contracts = {workspace = true}
pallet-insecure-randomness-collective-flip = {workspace = true}
pallet-utility = {workspace = true}

wetee-message-queue = {path = "../../pallets/message-queue", default-features = false}

wetee-app = {path = "../../pallets/wetee-app", default-features = false}
wetee-assets = {path = "../../pallets/wetee-assets", default-features = false}
wetee-dsecret = {path = "../../pallets/wetee-dsecret", default-features = false}
wetee-gov = {path = "../../pallets/wetee-gov", default-features = false}
wetee-gpu = {path = "../../pallets/wetee-gpu", default-features = false}
wetee-guild = {path = "../../pallets/wetee-guild", default-features = false}
wetee-org = {path = "../../pallets/wetee-org", default-features = false}
wetee-primitives = {path = "../../primitives", default-features = false}
wetee-project = {path = "../../pallets/wetee-project", default-features = false}
wetee-runtime-api = {path = "../../pallets/wetee-rpc/runtime-api", default-features = false, optional = true}
wetee-sudo = {path = "../../pallets/wetee-sudo", default-features = false}
wetee-task = {path = "../../pallets/wetee-task", default-features = false}
wetee-tee-bridge = {path = "../../pallets/wetee-tee-bridge", default-features = false}
wetee-treasury = {path = "../../pallets/wetee-treasury", default-features = false}
wetee-worker = {path = "../../pallets/wetee-worker", default-features = false}

[build-dependencies]
substrate-wasm-builder = {workspace = true, optional = true}

[features]
default = ["std"]

std = [
  "codec/std",
  "scale-info/std",
  "frame-executive/std",
  "frame-support/std",
  "frame-system-benchmarking?/std",
  "frame-system-rpc-runtime-api/std",
  "frame-system/std",
  "frame-benchmarking?/std",
  "frame-try-runtime?/std",
  "pallet-aura/std",
  "pallet-balances/std",
  "pallet-grandpa/std",
  "pallet-sudo/std",
  "pallet-timestamp/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "pallet-transaction-payment/std",
  "sp-api/std",
  "sp-block-builder/std",
  "sp-consensus-aura/std",
  "sp-consensus-grandpa/std",
  "sp-core/std",
  "sp-genesis-builder/std",
  "sp-inherents/std",
  "sp-offchain/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-std/std",
  "sp-storage/std",
  "sp-transaction-pool/std",
  "sp-version/std",
  "substrate-wasm-builder",
  "pallet-insecure-randomness-collective-flip/std",
  "wetee-message-queue/std",
  "pallet-utility/std",
  "pallet-contracts/std",
  "orml-traits/std",
  "orml-tokens/std",
  "wetee-primitives/std",
  "wetee-org/std",
  "wetee-sudo/std",
  "wetee-gov/std",
  "wetee-assets/std",
  "wetee-guild/std",
  "wetee-project/std",
  "wetee-worker/std",
  "wetee-app/std",
  "wetee-task/std",
  "wetee-gpu/std",
  "wetee-treasury/std",
  "wetee-dsecret/std",
  "wetee-tee-bridge/std",
  "wetee-runtime-api/std",
]

runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
  "frame-system-benchmarking/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-balances/runtime-benchmarks",
  "pallet-grandpa/runtime-benchmarks",
  "pallet-sudo/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]

try-runtime = [
  "frame-executive/try-runtime",
  "frame-support/try-runtime",
  "frame-system/try-runtime",
  "frame-try-runtime/try-runtime",
  "pallet-aura/try-runtime",
  "pallet-balances/try-runtime",
  "pallet-grandpa/try-runtime",
  "pallet-sudo/try-runtime",
  "pallet-timestamp/try-runtime",
  "pallet-transaction-payment/try-runtime",
  "sp-runtime/try-runtime",
]
