
//! Autogenerated weights for wetee_sudo

// Executed Command:
// ./target/debug/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-sudo
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-sudo/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for wetee_sudo.
pub trait WeightInfo {
	fn sudo() -> Weight;
	fn set_sudo_account() -> Weight;
	fn close_sudo() -> Weight;
}

/// Weights for wetee_sudo using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `WeteeSudo::CloseDao` (r:1 w:0)
	/// Proof: `WeteeSudo::CloseDao` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeteeSudo::Account` (r:1 w:0)
	/// Proof: `WeteeSudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeteeSudo::SudoTasks` (r:1 w:1)
	/// Proof: `WeteeSudo::SudoTasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeteeOrg::AppHubs` (r:1 w:0)
	/// Proof: `WeteeOrg::AppHubs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeteeOrg::OrgApps` (r:1 w:1)
	/// Proof: `WeteeOrg::OrgApps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391`
		//  Estimated: `3856`
		// Minimum execution time: 749_127_000 picoseconds.
		Weight::from_parts(751_402_000, 3856)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `WeteeSudo::CloseDao` (r:1 w:0)
	/// Proof: `WeteeSudo::CloseDao` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeteeSudo::Account` (r:1 w:1)
	/// Proof: `WeteeSudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_sudo_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `3605`
		// Minimum execution time: 325_156_000 picoseconds.
		Weight::from_parts(327_250_000, 3605)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeteeSudo::Account` (r:1 w:0)
	/// Proof: `WeteeSudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeteeSudo::CloseDao` (r:0 w:1)
	/// Proof: `WeteeSudo::CloseDao` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn close_sudo() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `3605`
		// Minimum execution time: 280_270_000 picoseconds.
		Weight::from_parts(281_753_000, 3605)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `WeteeSudo::CloseDao` (r:1 w:0)
	/// Proof: `WeteeSudo::CloseDao` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeteeSudo::Account` (r:1 w:0)
	/// Proof: `WeteeSudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeteeSudo::SudoTasks` (r:1 w:1)
	/// Proof: `WeteeSudo::SudoTasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeteeOrg::AppHubs` (r:1 w:0)
	/// Proof: `WeteeOrg::AppHubs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeteeOrg::OrgApps` (r:1 w:1)
	/// Proof: `WeteeOrg::OrgApps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391`
		//  Estimated: `3856`
		// Minimum execution time: 749_127_000 picoseconds.
		Weight::from_parts(751_402_000, 3856)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `WeteeSudo::CloseDao` (r:1 w:0)
	/// Proof: `WeteeSudo::CloseDao` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeteeSudo::Account` (r:1 w:1)
	/// Proof: `WeteeSudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_sudo_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `3605`
		// Minimum execution time: 325_156_000 picoseconds.
		Weight::from_parts(327_250_000, 3605)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeteeSudo::Account` (r:1 w:0)
	/// Proof: `WeteeSudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeteeSudo::CloseDao` (r:0 w:1)
	/// Proof: `WeteeSudo::CloseDao` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn close_sudo() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `140`
		//  Estimated: `3605`
		// Minimum execution time: 280_270_000 picoseconds.
		Weight::from_parts(281_753_000, 3605)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}