
//! Autogenerated weights for `wetee_tee_bridge`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-09-03, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-tee-bridge
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-tee-bridge/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_tee_bridge`.
pub trait WeightInfo {
	fn set_tee_api() -> Weight;
	fn ink_callback() -> Weight;
	fn call_ink() -> Weight;
	fn delete_call() -> Weight;
}

/// Weights for `wetee_tee_bridge` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn set_tee_api() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_716_000 picoseconds.
		Weight::from_parts(5_927_000, 0)
	}
	fn ink_callback() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_254_000 picoseconds.
		Weight::from_parts(5_697_000, 0)
	}
	fn call_ink() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_722_000 picoseconds.
		Weight::from_parts(7_030_000, 0)
	}
	fn delete_call() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_003_000 picoseconds.
		Weight::from_parts(5_235_000, 0)
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn set_tee_api() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_716_000 picoseconds.
		Weight::from_parts(5_927_000, 0)
	}
	fn ink_callback() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_254_000 picoseconds.
		Weight::from_parts(5_697_000, 0)
	}
	fn call_ink() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_722_000 picoseconds.
		Weight::from_parts(7_030_000, 0)
	}
	fn delete_call() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_003_000 picoseconds.
		Weight::from_parts(5_235_000, 0)
	}
}