
//! Autogenerated weights for `wetee_sudo`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-08-21, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `sgx`, CPU: `Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/wetee-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// wetee-sudo
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// packages/pallets/wetee-sudo/src/weights.rs
// --template
// ./hacks/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `wetee_sudo`.
pub trait WeightInfo {
	fn sudo() -> Weight;
	fn set_sudo_account() -> Weight;
	fn close_sudo() -> Weight;
}

/// Weights for `wetee_sudo` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `WeTEESudo::CloseDao` (r:1 w:0)
	/// Proof: `WeTEESudo::CloseDao` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::Account` (r:1 w:0)
	/// Proof: `WeTEESudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::SudoTasks` (r:1 w:1)
	/// Proof: `WeTEESudo::SudoTasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::AppHubs` (r:1 w:0)
	/// Proof: `WeTEEOrg::AppHubs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::OrgApps` (r:1 w:1)
	/// Proof: `WeTEEOrg::OrgApps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `479`
		//  Estimated: `3944`
		// Minimum execution time: 71_498_000 picoseconds.
		Weight::from_parts(72_689_000, 3944)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `WeTEESudo::CloseDao` (r:1 w:0)
	/// Proof: `WeTEESudo::CloseDao` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::Account` (r:1 w:1)
	/// Proof: `WeTEESudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_sudo_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `377`
		//  Estimated: `3842`
		// Minimum execution time: 39_030_000 picoseconds.
		Weight::from_parts(39_701_000, 3842)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::Account` (r:1 w:0)
	/// Proof: `WeTEESudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::CloseDao` (r:0 w:1)
	/// Proof: `WeTEESudo::CloseDao` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn close_sudo() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `377`
		//  Estimated: `3842`
		// Minimum execution time: 35_782_000 picoseconds.
		Weight::from_parts(36_214_000, 3842)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `WeTEESudo::CloseDao` (r:1 w:0)
	/// Proof: `WeTEESudo::CloseDao` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::Account` (r:1 w:0)
	/// Proof: `WeTEESudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::SudoTasks` (r:1 w:1)
	/// Proof: `WeTEESudo::SudoTasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::AppHubs` (r:1 w:0)
	/// Proof: `WeTEEOrg::AppHubs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::OrgApps` (r:1 w:1)
	/// Proof: `WeTEEOrg::OrgApps` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn sudo() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `479`
		//  Estimated: `3944`
		// Minimum execution time: 71_498_000 picoseconds.
		Weight::from_parts(72_689_000, 3944)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `WeTEESudo::CloseDao` (r:1 w:0)
	/// Proof: `WeTEESudo::CloseDao` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::Account` (r:1 w:1)
	/// Proof: `WeTEESudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_sudo_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `377`
		//  Estimated: `3842`
		// Minimum execution time: 39_030_000 picoseconds.
		Weight::from_parts(39_701_000, 3842)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `WeTEEOrg::Daos` (r:1 w:0)
	/// Proof: `WeTEEOrg::Daos` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::Account` (r:1 w:0)
	/// Proof: `WeTEESudo::Account` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `WeTEESudo::CloseDao` (r:0 w:1)
	/// Proof: `WeTEESudo::CloseDao` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn close_sudo() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `377`
		//  Estimated: `3842`
		// Minimum execution time: 35_782_000 picoseconds.
		Weight::from_parts(36_214_000, 3842)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}